os:
  - linux
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - TRAVIS_RUST_VERSION=stable
    - RUST_BACKTRACE=1
    - CI_HOME=`pwd`

before_install:
  - source ./ci/travis_setup.sh

install:
  - rustc -V
  - pip install .

script:
  - python ./tests/test_py_to_rs.py
  - python ./tests/test_rs_to_py.py
  - cargo clippy --manifest-path ./src/librustypy/Cargo.toml
  - cargo test --manifest-path ./src/librustypy/Cargo.toml
